@startuml
    class Pessoa {
        Nome: String
        Idade: Integer
        apresentar(): void
    }
    class Carro {
        Marca: String
        Modelo: String
        Ano: Integer
        exibirInformacoes(): void
    }

    class Produto { 
        Nome: String
        preco: float
        quantidade: int
        calcularValorTotal(): float
    }

    Produto <|-- Carro 
@enduml